import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import ProductCard from "@/components/product/productCart";
import { useEffect, useState } from "react";
import Countdown from "react-countdown";
import LifeStyleCard from "@/components/lifestyleCard";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/pagination";
// import "./styles.css";
import { FreeMode, Pagination } from "swiper";
import FromPeopleCard from "@/components/frompeopleCard";
import ProductModal from "@/components/product/productModal";
import { useSelector } from "react-redux";
import db from "@/utils/db";
import Product from "@/models/Product";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]";
import User from "@/models/User";

export default function Home({ products, user }) {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [productId, setProductId] = useState("");
  const [load, setLoad] = useState(false);
  useEffect(() => {
    setLoad(true);
  }, []);
  const cart = useSelector((state) => state.cartSlice.cart);

  const Completionist = () => <span>You are good to go!</span>;

  // Renderer callback with condition
  const renderer = ({ hours, minutes, seconds, completed }) => {
    if (completed) {
      // Render a completed state
      return <Completionist />;
    } else {
      // Render a countdown
      return (
        <span>
          {hours}:{minutes}:{seconds}
        </span>
      );
    }
  };

  const handleModal = (id) => {
    setProductId(id);
    setIsModalOpen(true);
  };

  return (
    <>
      <Head>
        <title>RFC Bakliyat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.main}>
        <ProductModal
          productId={productId}
          isModalOpen={isModalOpen}
          setIsModalOpen={setIsModalOpen}
          cart={cart}
          user={user}
          products={products}
        />
        <div className={styles.containers}>
          <div className={styles.containers__left}>
            <h4>22₺'den Başlayan Fiyatlarla</h4>
            <h1>
              <b style={{ color: "#392c2b" }}> Tarladan</b> Hemen Kapınızın
              Önüne
            </h1>
            <p>Sadece bu haftasonu, ayın geri kalanında.</p>
            <div className={styles.containers__left_bottom}>
              <Link href="/shop">
                <button className={styles.secondary_button}>Satın Al</button>
              </Link>
              <Image
                src={"/images/arrow.svg"}
                height={40}
                width={40}
                alt="sağlıklı ol resmi"
              />
              <Image
                src={"/images/healthy.png"}
                height={50}
                width={110}
                alt="sağlıklı ol resmi"
              />
            </div>
          </div>
          <div className={styles.containers__right}>
            <Image
              src={"/images/basket.png"}
              height={500}
              width={700}
              alt="sepet resmi"
            />
          </div>
        </div>
      </div>
      <div className={styles.about}>
        <Link href="/about">
          <div>
            <Image
              src={"/images/about/about1.svg"}
              height={100}
              width={100}
              alt="about resmi 1"
            />
            <h2>Bugün Yetiştirilir, Yarın Teslim Edilir</h2>
            <p>
              Organik meyve ve sebzelerimiz, kendi topraklarında sadece doğal
              gübre kullanan çiftçiler tarafından yetiştirilmektedir.
            </p>
          </div>
        </Link>

        <Link href="/about">
          <div>
            <Image
              src={"/images/about/about2.svg"}
              height={100}
              width={100}
              alt="about resmi 1"
            />
            <h2>Teslimat Hızımız Çok Hızlı</h2>
            <p>
              Bu kolay ve uygun fiyatlı market teslimat hizmetleriyle zamandan,
              paradan ve biraz da akıl sağlığından tasarruf edin.
            </p>
          </div>
        </Link>
        <Link href="/about">
          <div>
            <Image
              src={"/images/about/about3.svg"}
              height={100}
              width={100}
              alt="about resmi 1"
            />
            <h2>%100 Tamamen Organik</h2>
            <p>
              %100 tamamen kendi üretimimiz olan ürünlerimizi sizlerle
              buluşturuyoruz.
            </p>
          </div>
        </Link>
      </div>
      <div className={styles.topCategories}>
        <div className={styles.topCategories__title}>
          <h2>Ürünler</h2>
        </div>
        <div className={styles.topCategories__body}>
          {products?.map((product) => (
            <ProductCard
              key={product._id}
              product={product}
              user={user}
              cart={cart}
              handleModal={handleModal}
            />
          ))}
        </div>
      </div>
      <div className={styles.flashDeal}>
        <div className={styles.container}>
          <div className={styles.flashDeal__kasa}>
            <Image
              src={"/images/meyvekasasi.png"}
              width={612}
              height={505}
              alt="kasa resmi"
            />
          </div>
          <div className={styles.flashDeal__infos}>
            <h4>Sınırlı Süre İçin Geçerli Teklif</h4>
            <h2>Organik Meyve Kasası</h2>
            <p>
              Organik gıdalar, uygun sağlık bakımı almak için güvenebileceğimiz
              tek kaynaktır. Organik gıda en besleyici gıdadır ve herkes
              tarafından tüketilmelidir.
            </p>
            {load && <Countdown date={new Date(2023, 2, 27)} />}
            <Link href="/shop">
              <button className={styles.secondary_button}>
                Tüm İndirimleri Göster
              </button>
            </Link>
          </div>
        </div>
      </div>
      <div className={styles.bestSelling}>
        <div className={styles.container}>
          <div className={styles.bestSelling__top}>
            <div className={styles.bestSelling__top_left}>
              <h2>En Çok Satılanlar</h2>
            </div>
            <div className={styles.bestSelling__top_right}>
              <ul>
                <li className={styles.active}>Tahıl</li>
                <li>Meyve</li>
                <li>Sebze</li>
              </ul>
            </div>
          </div>
          <div className={styles.bestSelling__body}>
            {products?.map((product, i) => {
              return (
                <ProductCard
                  key={i}
                  cart={cart}
                  handleModal={handleModal}
                  product={product}
                  user={user}
                />
              );
            })}
          </div>
        </div>
      </div>
      <div className={styles.bestSelling}>
        <div className={styles.container}>
          <div className={styles.bestSelling__top}>
            <div className={styles.bestSelling__top_left}>
              <h2>Taze Ürünler</h2>
            </div>
            <div className={styles.bestSelling__top_right}>
              <ul>
                <li className={styles.active}>Elma</li>
                <li>Çilekler</li>
                <li>Erik</li>
              </ul>
            </div>
          </div>
          <div className={styles.bestSelling__body}>
            {products?.map((product, i) => {
              return (
                <ProductCard
                  key={i}
                  cart={cart}
                  user={user}
                  handleModal={handleModal}
                  product={product}
                />
              );
            })}
          </div>
        </div>
      </div>
      <div className={styles.lifestyle}>
        <div className={styles.container}>
          <div className={styles.lifestyle__title}>
            <h2>Yaşam Tarzına Göre</h2>
          </div>
          <div className={styles.lifestyle__body}>
            {lifestyle.map((style, i) => (
              <LifeStyleCard key={i} data={style} />
            ))}
          </div>
        </div>
      </div>
      <div className={styles.services}>
        <div className={styles.container}>
          {services.map((service, i) => (
            <div key={i} className={styles.services__service}>
              <Image
                src={service.img}
                height="150"
                width={150}
                alt={service.name}
              />
              <h3>{service.name}</h3>
              <p>{service.desc}</p>
            </div>
          ))}
        </div>
      </div>
      <div className={styles.frompeople}>
        <div className={styles.container}>
          <div className={styles.frompeople__title}>
            <h5>Sizden Gelenler</h5>
          </div>
          <div className={styles.frompeople__titles}>
            <h5>Sizden Gelenler</h5>
          </div>
          <div className={styles.frompeople__body}>
            <Swiper
              slidesPerView={3}
              spaceBetween={2}
              freeMode={true}
              pagination={{
                clickable: true,
              }}
              breakpoints={{
                400: {
                  slidesPerView: 1,
                  spaceBetween: 20,
                },
                500: {
                  slidesPerView: 1,
                  spaceBetween: 20,
                },
                640: {
                  slidesPerView: 1,
                  spaceBetween: 20,
                },
                768: {
                  slidesPerView: 2,
                  spaceBetween: 40,
                },
                1024: {
                  slidesPerView: 3,
                  spaceBetween: 50,
                },
              }}
              modules={[FreeMode, Pagination]}
              className="mySwiper"
            >
              {frompeople.map((comment, i) => (
                <SwiperSlide key={i}>
                  <FromPeopleCard comment={comment} />
                </SwiperSlide>
              ))}
            </Swiper>
          </div>
        </div>
      </div>
    </>
  );
}

/* export const products = [
  {
    id: 1,
    name: "Kuru Üzüm ve Karışık Mix",
    price: 12.0,
    rate: 4.5,
    images: ["/images/products/drygrape.jpg"],
    description: "Domatesler Domatesler 10 Numara domatesler",
    stock: 2,
  },
  {
    id: 2,
    name: "Dünyanın En iyi Fasullesi",
    price: 7.5,
    rate: 4.5,
    images: ["/images/products/fasulle.jpg"],
    description: "Domatesler Domatesler 10 Numara domatesler",
    stock: 2,
  },
  {
    id: 3,
    name: "Çakmağı Görünce Pişen Nohut",
    price: 10.5,
    rate: 3.5,
    images: ["/images/products/nohut.jpg"],
    description: "Domatesler Domatesler 10 Numara domatesler",
    stock: 2,
  },
  {
    id: 4,
    name: "Kuru Üzüm ve Karışık Mix",
    price: 12.0,
    rate: 4.5,
    images: ["/images/products/drygrape.jpg"],
    description: "Domatesler Domatesler 10 Numara domatesler",
    stock: 2,
  },
  {
    id: 5,
    name: "Dünyanın En iyi Fasullesi",
    price: 7.5,
    rate: 4.5,
    images: ["/images/products/fasulle.jpg"],
    description: "Domatesler Domatesler 10 Numara domatesler",
    stock: 2,
  },
  {
    id: 6,
    name: "Çakmağı Görünce Pişen Nohut",
    price: 10.5,
    rate: 3.5,
    images: ["/images/products/nohut.jpg"],
    description: "Domatesler Domatesler 10 Numara domatesler",
    stock: 2,
  },
  {
    id: 7,
    name: "Kuru Üzüm ve Karışık Mix",
    price: 12.0,
    rate: 4.5,
    images: ["/images/products/drygrape.jpg"],
    description: "Domatesler Domatesler 10 Numara domatesler",
    stock: 2,
  },
  {
    id: 8,
    name: "Dünyanın En iyi Fasullesi",
    price: 7.5,
    rate: 4.5,
    images: ["/images/products/fasulle.jpg"],
    description: "Domatesler Domatesler 10 Numara domatesler",
    stock: 2,
  },
  {
    id: 9,
    name: "Çakmağı Görünce Pişen Nohut",
    price: 10.5,
    rate: 3.5,
    images: ["/images/products/nohut.jpg"],
    description: "Domatesler Domatesler 10 Numara domatesler",
    stock: 2,
  },
]; */

const lifestyle = [
  {
    name: "Vegan",
    img: "/images/lifestyle/vegan.svg",
  },
  {
    name: "Glutensiz",
    img: "/images/lifestyle/glutenfree.svg",
  },
  {
    name: "Paleo",
    img: "/images/lifestyle/paleo.svg",
  },
  {
    name: "Ketojenik",
    img: "/images/lifestyle/keto.svg",
  },
  {
    name: "Pesketeryan",
    img: "/images/lifestyle/flexitarian.svg",
  },
  {
    name: "Oruç",
    img: "/images/lifestyle/fasting.svg",
  },
];
const services = [
  {
    name: "Gel Al",
    desc: "Nakliye ücretinden kaçınırken siparişlerinizi daha hızlı alın.",
    img: "/images/services/service1.png",
  },
  {
    name: "Yerel Teslimat",
    desc: "Talebiniz üzerine 100% geri dönüştürülebilir kağıt torbalar kullanıyoruz..",
    img: "/images/services/service2.png",
  },
  {
    name: "Bilinçli Tüketiciler",
    desc: "Küçük çiftçileri ve üreticiyi destekliyoruz.",
    img: "/images/services/service3.png",
  },
  {
    name: "Lezzetli ve Yeni Ürünler",
    desc: "Her gün yediğiniz taze ürünler ile iyi hissedin.",
    img: "/images/services/service4.png",
  },
];
export const frompeople = [
  {
    fullName: "Resul ÖZTÜRK",
    comment:
      "Şiddetle tavsiye ediyorum! RFC Bakliyat kapıya teslim ediliyor ve dürüst olmak gerekirse, mağazaya kıyasla daha ucuz görünüyor.",
    img: "/images/frompeople/people1.jpg",
  },
  {
    fullName: "Cevher KARAMAN",
    comment:
      "RFC Bakliyat her zaman normalde mağazada görmediğim benzersiz bir ürün yelpazesine sahip. Ürünleri birinci sınıf.",
    img: "/images/frompeople/people2.jpg",
  },
  {
    fullName: "Cüneyt BAYAR",
    comment:
      "RFC Bakliyat Market haftasından ne güzel bir vurgun! Tam anlamıyla bir şefin rüyası. Kesinlikle çalışacak çok şey var.",
    img: "/images/frompeople/people3.jpg",
  },
  {
    fullName: "Hanife YÜCE",
    comment:
      "Şiddetle tavsiye ediyorum! RFC Bakliyat kapıya teslim ediliyor ve dürüst olmak gerekirse, mağazaya kıyasla daha ucuz görünüyor.",
    img: "/images/frompeople/people4.jpg",
  },
];

export async function getServerSideProps(context) {
  const { req, res } = context;
  const session = await getServerSession(req, res, authOptions);
  await db.connectDb();
  const products = await Product.find({})?.sort({ createdAt: 1 }).lean();
  const user = await User.find({ email: session?.user.email })?.lean();
  const userInfo = {
    email: user[0]?.email,
    name: user[0]?.name,
    username: user[0]?.username,
    wishlist: user[0]?.wishlist,
  };
  await db.disconnectDb();
  return {
    props: {
      products: JSON.parse(JSON.stringify(products)),
      user: JSON.parse(JSON.stringify(userInfo)),
    },
  };
}
